/* Publication list for joshuaweidlich.github.io
   One line per publication, newest first. To add one, copy a line and change it.
   y year · a authors · t title · v journal or venue · d DOI · l other link
   p PDF on the old WordPress site · pu PDF at any full address · b old blog post
   s research update page in the "updates" folder · k topic (fb, me, sp, ge, te)
   x type (ch chapter, co conference paper, th dissertation, pr preprint, ta talk) */
window.PUBS=[
{y:2026,a:'Weidlich, J.',t:'Which inference is at risk? Assessment validity reasoning and generative AI',v:'<i>Assessment & Evaluation in Higher Education</i>, 1–20',d:'10.1080/02602938.2026.2734795',k:'fb'},
{y:2026,a:'Lawson, A. P., Martella, A. M., Weidlich, J., Mulders, M., & Buchner, J.',t:'Color me confounded: A critical analysis of media comparisons on ChatGPT in education',v:'<i>Computers & Education</i>, 105701', d: '10.1016/j.compedu.2026.105701', k:'me'},
{y:2026,a:'Kalz, M., Schulze, A., Meeh, H., & Weidlich, J.',t:'Validity evidence for the internal structure of the peer feedback orientation scale',v:'<i>Technology, Knowledge and Learning</i>, 1–16',d:'10.1007/s10758-026-09972-9',k:'fb'},
{y:2026,a:'Weidlich, J., & Kalz, M.',t:'How well does teacher education prepare for teaching with technology? A TPACK-based investigation at a university of education',v:'<i>European Journal of Teacher Education, 49</i>(1), 168–188',d:'10.1080/02619768.2023.2243645',k:'te'},
{y:2026,a:'Weidlich, J., Gotsch, F., Schudel, K., Marusic-Würscher, C., Bolten, H., Luger, S., Bütler, D., Wohlfender, B., Mazzarella, J., & Maag Merki, K.',t:'The medium is not the message: Message features in teacher, peer, and AI feedback help explain the divergence of perceptions and performance',v:'<i>SocArXiv</i>',k:'fb',x:'pr'},
{y:2026,a:'Weidlich, J.',t:'Do we really care about that? Deep conceptual problems subvert current media comparison practices',v:'Annual Meeting of the American Educational Research Association (AERA), Los Angeles, USA',k:'me',x:'ta'},
{y:2025,a:'Weidlich, J., Gašević, D., Drachsler, H., & Kirschner, P.',t:'ChatGPT in education: An effect in search of a cause',v:'<i>Journal of Computer Assisted Learning, 41</i>, e70105',d:'10.1111/jcal.70105',s:'chatgpt-in-education',p:'2025/09/weidlich-et-al-2025-chatgpt-in-education.pdf',k:'fb'},
{y:2025,a:'Weidlich, J., Gotsch, F., Schudel, K., Marusic-Würscher, C., Mazzarella, J., Bolten, H., Bütler, D., Luger, S., Wohlfender, B., & Maag Merki, K.',t:'Teacher, peer, or AI? Comparing effects of feedback sources in higher education',v:'<i>Computers and Education Open, 9</i>, 100300',d:'10.1016/j.caeo.2025.100300',pu:'https://www.ife.uzh.ch/dam/jcr:240d1fe5-81a5-4670-8e0d-b8ab9548d498/Weidlich%20et%20al_2025_Teacher%20peer%20or%20AI_Comparing%20effects%20of%20feedback%20sources%20in%20higher%20education.pdf',s:'teacher-peer-or-ai',k:'fb'},
{y:2025,a:'Weidlich, J., Fink, A., Frey, A., Jivet, I., Gombert, S., Menzel, L., Giorgashvili, T., Yau, J., & Drachsler, H.',t:'Highly informative feedback using learning analytics: How feedback literacy moderates student perceptions of feedback',v:'<i>International Journal of Educational Technology in Higher Education, 22</i>(1), 43',d:'10.1186/s41239-025-00539-9',s:'highly-informative-feedback',p:'2025/09/weidlich-et-al-2025-hila-feedback-literacy.pdf',k:'fb'},
{y:2025,a:'Weidlich, J., Jivet, I., Woitt, S., Orhan Göksün, D., Kraus, J., & Drachsler, H.',t:'The student feedback literacy instrument (SFLI): Multilingual validation and introduction of a short-form version',v:'<i>Assessment & Evaluation in Higher Education</i>, 1–17',d:'10.1080/02602938.2025.2451729',s:'student-feedback-literacy-instrument',p:'2025/09/weidlich-et-al-2025-feedback-literacy-sfli-v2.pdf',k:'fb'},
{y:2025,a:'Richter, E., Spitzer, M. W. H., Morgan, A., Frede, L., Weidlich, J., & Moeller, K.',t:'Large language models outperform humans in identifying neuromyths but show sycophantic behavior in applied contexts',v:'<i>Trends in Neuroscience and Education, 39</i>, 100255',l:'https://www.sciencedirect.com/science/article/pii/S2211949325000092',k:'fb'},
{y:2025,a:'Xu, K. M., Lin, L., Gorter, M., Schneider, S., Weidlich, J., Davis, R. O., Kreijns, K., & de Groot, R.',t:'Social presence: A key factor in embedding a pedagogical agent into online learning in primary education',v:'<i>British Journal of Educational Technology</i>',d:'10.1111/bjet.70006',k:'sp'},
{y:2024,a:'Weidlich, J., Fink, A., Jivet, I., Yau, J., Giorgashvili, T., Drachsler, H., & Frey, A.',t:'Emotional and motivational effects of automated and personalized formative feedback: The role of reference frames',v:'<i>Journal of Computer Assisted Learning</i>',d:'10.1111/jcal.13024',b:'2024/07/09/new-pub-effects-of-automated-personalized-feedback-on-emotions-and-motivation/',k:'fb'},
{y:2024,a:'Kreijns, K., Weidlich, J., & Kirschner, P.',t:'Pitfalls of social interaction in online group learning',v:'In Y. Zheng (Ed.), <i>The Cambridge Handbook of Cyberbehavior</i>. Cambridge University Press',p:'2024/08/kreijns-et-al-2024-pitfalls-cambridge-handbook.pdf',k:'sp',x:'ch'},
{y:2024,a:'Kube, D., Weidlich, J., Kreijns, K., & Drachsler, H.',t:'Addressing gender in STEM classrooms: The impact of gender bias on women scientists’ experiences in higher education careers in Germany',v:'<i>Education and Information Technologies</i>, 1–28',p:'2024/04/kube-et-al-2024-gender-bias-in-stem-gcm-study.pdf',k:'ge'},
{y:2024,a:'Kube, D., Gombert, S., John, N., Weidlich, J., Kreijns, K., & Drachsler, H.',t:'Escaping binary gender roles: Gender diversity dynamics in a CSCL escape game',v:'<i>Journal of Computer Assisted Learning</i>',p:'2024/04/kube-et-al-2024-escaping-binary-gender-roles.pdf',k:'ge'},
{y:2024,a:'Kreijns, K., Yau, J., Weidlich, J., & Weinberger, A.',t:'Towards a comprehensive framework of social presence for online, hybrid, and blended learning',v:'<i>Frontiers in Education, 8</i>, 1286594',d:'10.3389/feduc.2023.1286594',p:'2024/04/kreijns-et-al-2024-comprehensive-framework.pdf',k:'sp'},
{y:2023,a:'Kube, D., Gombert, S., Suter, B., Weidlich, J., Kreijns, K., & Drachsler, H.',t:'Hacking gender in computer-supported collaborative learning: The experience of being in mixed-gender teams at a computer science hackathon',v:'<i>Journal of Computer Assisted Learning</i>, 1–15',d:'10.1111/jcal.12905',k:'ge'},
{y:2023,a:'Weidlich, J., Yau, J., & Kreijns, K.',t:'Social presence and psychological distance: A construal level account for online distance learning',v:'<i>Education and Information Technologies</i>, 1–23',d:'10.1007/s10639-023-12289-0',b:'2023/11/24/new-pub-social-presence-and-psychological-distance/',k:'sp'},
{y:2023,a:'Woitt, S., Weidlich, J., Jivet, I., Göksün, D., Drachsler, H., & Kalz, M.',t:'Students’ feedback literacy in higher education: An initial scale validation study',v:'<i>Teaching in Higher Education</i>, 1–20',d:'10.1080/13562517.2023.2263838',b:'2023/10/20/new-publication-a-simple-scale-for-measuring-student-feedback-literacy/',k:'fb'},
{y:2023,a:'Weidlich, J., Hicks, B., & Drachsler, H.',t:'Causal reasoning with causal graphs in educational technology research',v:'<i>Educational Technology Research and Development</i>, 1–19',d:'10.1007/s11423-023-10241-0',k:'me'},
{y:2022,a:'Weidlich, J., Gašević, D., & Drachsler, H.',t:'Causal inference and bias in learning analytics: A primer on pitfalls using directed acyclic graphs',v:'<i>Journal of Learning Analytics, 9</i>(3), 1–17',d:'10.18608/jla.2022.7577',k:'me'},
{y:2022,a:'Kube, D., Weidlich, J., Jivet, I., Kreijns, K., & Drachsler, H.',t:'“Gendered differences versus doing gender”: A systematic review on the role of gender in CSCL',v:'<i>Unterrichtswissenschaft</i>',d:'10.1007/s42010-022-00153-y',p:'2022/08/kube-et-al-2022-gender-cscl-uwis.pdf',k:'ge'},
{y:2022,a:'Weidlich, J., Göksün, D. O., & Kreijns, K.',t:'Extending social presence theory: Social presence divergence and interaction integration in online distance learning',v:'<i>Journal of Computing in Higher Education</i>',d:'10.1007/s12528-022-09325-2',b:'2023/02/03/new-publication-extending-social-presence-theory/',k:'sp'},
{y:2022,a:'Kreijns, K., Henderikx, M., & Weidlich, J.',t:'Productivity in online CSCL groups: A Rasch analysis approach to the preliminary validation of the productivity scale',v:'In <i>Proceedings of INTED2022</i>. IATED',p:'2022/03/kreijns-et-al-2022-inted2022.pdf',b:'2022/03/15/new-publication-group-productivity-in-cscl/',k:'sp',x:'co'},
{y:2022,a:'Rosar, M., & Weidlich, J.',t:'Creative students in self-paced online learning environments: An experimental exploration of the interaction of visual design and creativity',v:'<i>Research and Practice in Technology Enhanced Learning, 17</i>(8)',p:'2022/02/rosar-weidlich-2022-creative-students.pdf',b:'2022/02/25/new-publication-student-creativity-in-learning-environment-design/',k:'te'},
{y:2022,a:'Fominykh, M., Weidlich, J., Kalz, M., & Hybertsen, I. D.',t:'What do they TEL(L)? A systematic analysis of master programs in technology-enhanced learning',v:'<i>International Journal of Educational Technology in Higher Education, 19</i>(1), 1–25',d:'10.1186/s41239-021-00305-7',b:'2022/01/06/new-publication-systematic-analysis-of-tel-edtech-masters-programs/',k:'te'},
{y:2021,a:'Weidlich, J., Kreijns, K., & Bastiaens, T.',t:'Individual differences in perceptions of social presence: Exploring the role of personality in online distance learning',v:'<i>Open Education Studies, 3</i>',p:'2021/11/weidlich-et-al-2021-oes-personality-and-sp.pdf',b:'2021/12/14/new-publication-in-open-education-studies/',k:'sp'},
{y:2021,a:'Weidlich, J.',t:'Presence at a distance: Empirical investigations toward understanding, modeling, and enhancing social presence in online distance learning environments',v:'Doctoral dissertation, FernUniversität in Hagen',p:'2021/11/weidlich_diss_for_online_title-page.pdf',k:'sp',x:'th'},
{y:2021,a:'Weidlich, J., & Kalz, M.',t:'Exploring predictors of instructional resilience during emergency remote teaching in higher education',v:'<i>International Journal of Educational Technology in Higher Education, 18</i>, 41',b:'2021/08/09/what-is-instructional-resilience/',k:'te'},
{y:2021,a:'Kreijns, K., Henderikx, M., & Weidlich, J.',t:'Measuring social space in online group learning: Preliminary validation of the social space scale using the Rasch analysis approach',v:'In <i>EdMedia + Innovate Learning</i> (pp. 445–458). AACE',p:'2021/11/kreijns-et-al-edmedia-2021-social-space.pdf',k:'sp',x:'co'},
{y:2021,a:'Kreijns, K., Xu, K. M., & Weidlich, J.',t:'Social presence: Conceptualization and measurement',v:'<i>Educational Psychology Review</i>',p:'2021/06/kreijns-et-al-2021-epr-socialpresenceconceptualizatio.pdf',b:'2021/12/14/new-publication-in-educational-psychology-review/',k:'sp'},
{y:2020,a:'Kreijns, K., Bijker, M., & Weidlich, J.',t:'A Rasch analysis approach to the development and validation of a social presence measure',v:'In <i>Rasch Measurement</i> (pp. 197–221). Springer',p:'2020/04/kreijns-bijker-weidlich-2020-rasch-approach-to-measuring-sp-chapter.pdf',k:'sp',x:'ch'},
{y:2019,a:'Weidlich, J., & Bastiaens, T. J.',t:'Pathway to presence: An investigation of ambient awareness in online learning environments',v:'<i>Interactive Learning Environments, 30</i>(2), 262–275',p:'2019/09/weidlich-bastiaens-2019-pathway-to-presence-an-investigation-of-ambient-awareness-in-online-learning-environments.pdf',b:'2019/09/06/new-paper-published-in-interactive-learning-environments/',k:'sp'},
{y:2019,a:'Weidlich, J., & Bastiaens, T. J.',t:'Designing sociable online learning environments and enhancing social presence: An affordance enrichment approach',v:'<i>Computers & Education, 142</i>, 103622',p:'2019/09/weidlich-bastiaens-2019-cae-designing-sociable.pdf',b:'2019/07/22/new-paper-published-in-computers-education/',k:'sp'},
{y:2019,a:'Bovermann, K., Habla, S., Weidlich, J., & Bastiaens, T.',t:'Better together? A case study comparison of individualistic vs. collectivistic gamification design',v:'In <i>EdMedia + Innovate Learning</i> (pp. 1079–1088). AACE',p:'2020/12/bovermann-habla-weidlich-bastiaens-2019-better-together_-e28093-a-case-study-comparison-of-individualistic-vs.-collectivistic-gamification-design.pdf',k:'te',x:'co'},
{y:2018,a:'Weidlich, J., Kreijns, K., Rajagopal, K., & Bastiaens, T. J.',t:'What social presence is, what it isn’t, and how to measure it: A work in progress',v:'In <i>Proceedings of EdMedia: World Conference on Educational Media and Technology</i> (pp. 2135–2143). AACE',p:'2019/09/weidlich-et-al-2018-what-social-presence-is.pdf',k:'sp',x:'co'},
{y:2018,a:'Bovermann, K., Weidlich, J., & Bastiaens, T. J.',t:'Online learning readiness and attitudes towards gaming in gamified online learning: A mixed methods case study',v:'<i>International Journal of Educational Technology in Higher Education, 15</i>, 27',p:'2019/09/bovermann-et-al-2018-gamification-and-online-learning.pdf',k:'te'},
{y:2018,a:'Weidlich, J., & Bastiaens, T. J.',t:'Technology matters: The impact of transactional distance on satisfaction in online distance learning',v:'<i>International Review of Research in Open and Distributed Learning, 19</i>(3), 222–242',p:'2019/09/weidlich-bastiaens-2018-technology-matters.pdf',k:'sp'},
{y:2017,a:'Weidlich, J., & Bastiaens, T. J.',t:'Explaining social presence and the quality of online learning with the SIPS model',v:'<i>Computers in Human Behavior, 72</i>, 479–487',p:'2019/09/weidlich-bastiaens_2017_-social-presence_sips_chb.pdf',k:'sp'}
];
